name: web-configs
up:
  - node:
      version: v22.14.0
      package_manager: pnpm@10.11.0

commands:
  __default__: start
  check: pnpm run check
  lint: pnpm run lint
  start: echo "Running web-configs is not really a concept that makes sense."
  test: pnpm run test
  generate: pnpm run generate
