module.exports = {
  'order/properties-order': [
    {
      order: 'strict',
      properties: [
        'content',
      ],
    },
    {
      order: 'strict',
      properties: [
        'position',
        'z-index',
        'top',
        'bottom',
        'left',
        'right',
      ],
    },
    {
      order: 'strict',
      properties: [
        'transform',
        'transform-origin',
      ],
    },
    {
      order: 'strict',
      properties: [
        'box-sizing',
        'display',
        'overflow',
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'order',
        'align-self',
        'flex-direction',
        'flex-wrap',
        'justify-content',
        'align-items',
        'align-content',
        'height',
        'width',
        'margin',
        'margin-top',
        'margin-bottom',
        'margin-left',
        'margin-right',
        'padding',
        'padding-top',
        'padding-bottom',
        'padding-left',
        'padding-right',
      ],
    },
    {
      order: 'strict',
      properties: [
        'background',
        'background-color',
        'background-size',
        'background-position',
        'background-repeat',
        'border',
        'border-top',
        'border-bottom',
        'border-left',
        'border-right',
        'outline',
        'box-shadow',
        'border-radius',
      ],
    },
    {
      order: 'strict',
      properties: [
        'font',
        'font-size',
        'font-weight',
        'font-style',
        'font-smoothing',
        'font-feature-settings',
        'line-height',
        'color',
        'text-align',
        'white-space',
        'vertical-align',
        'text-decoration',
      ],
    },
    {
      order: 'strict',
      properties: [
        'transition',
      ],
    },
    {
      unspecified: 'ignore',
    },
  ],
  'order/properties-alphabetical-order': false,
};
