name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed in 3 weeks if no further activity occurs.'
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed in 3 weeks if no further activity occurs.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          days-before-stale: 180
          days-before-close: 180
